name: pytorch
channels:
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.3
  - openssl=1.1.1w
  - pip=25.2
  - python=3.10.4
  - readline=8.1.2
  - setuptools=78.1.1
  - sqlite=3.38.2
  - tk=8.6.11
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.2.5
  - libuuid=1.0.3
  - zlib=1.2.11
  - pip:
    - astropy==6.1.7
    - astropy-iers-data==0.2025.10.6.0.35.25
    - attrs==25.4.0
    - bidict==0.23.1
    - bottleneck==1.6.0
    - braceexpand==0.1.7
    - certifi==2025.10.5
    - charset-normalizer==3.4.3
    - click==8.3.0
    - cmake==4.1.0
    - contourpy==1.3.2
    - cycler==0.12.1
    - filelock==3.20.0
    - fitsio==1.2.6
    - fonttools==4.60.1
    - fsspec==2025.9.0
    - h5py==3.14.0
    - hf-xet==1.1.10
    - huggingface-hub==0.35.3
    - idna==3.10
    - imageio==2.37.0
    - iqrm==0.2.0
    - jinja2==3.1.6
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - lazy_loader==0.4
    - lit==18.1.8
    - llvmlite==0.44.0
    - markdown-it-py==4.0.0
    - markupsafe==3.0.3
    - matplotlib==3.10.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - networkx==3.4.2
    - numba==0.61.2
    - numpy==1.26.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - opencv-python==4.11.0.86
    - packaging==25.0
    - pandas==2.3.0
    - pillow==11.3.0
    - psutil==5.8.0
    - pyerfa==2.0.1.5
    - pygments==2.19.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - requests==2.32.5
    - rich==14.1.0
    - safetensors==0.6.2
    - scikit-image==0.25.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - "git+https://github.com/FRBs/sigpyproc3@v1.1.0#egg=sigpyproc"
    - six==1.17.0
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - tifffile==2025.5.10
    - timm==1.0.20
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tqdm==4.67.1
    - triton==2.0.0
    - typing_extensions==4.15.0
    - urllib3==2.5.0

